<%@ page contentType="text/html;charset=UTF-8"%><footer class="footer-wrap"><div class="fw-content clearfix">
<dl class="fw-normal-wrap">
<dt class="fw-about-title fw-normal-dt">
<a href="/help/aboutus" target="_blank">
<i class="icon-fw-loan"></i>
<span class="fw-title">人人分期</span>
</a>
</dt>
<dd>
<a class="fw-normal-link" href="/help/aboutus" target="_blank">关于我们</a>
</dd>
<dd>
<a class="fw-normal-link" href="/help/qualified" target="_blank">分期资格</a>
</dd>
<dd>
<a class="fw-normal-link" href="/help/approve" target="_blank">认证流程</a>
</dd>
<dd>
<a class="fw-normal-link" href="/help/buyprocess" target="_blank">购买流程</a>
</dd>
</dl>
<dl class="fw-normal-wrap">
<dt class="fw-about-title fw-normal-dt">
<a href="/help/billinstruction" target="_blank">
<i class="icon-fw-repayment"></i>
<span class="fw-title">还款方式</span>
</a>
</dt>
<dd>
<a class="fw-normal-link" href="/help/billinstruction" target="_blank">账单说明</a>
</dd>
<dd>
<a class="fw-normal-link" href="/help/reimbursement" target="_blank">还款流程</a>
</dd>
</dl>
<dl class="fw-normal-wrap">
<dt class="fw-about-title fw-normal-dt">
<a href="/help/authenticguarantee" target="_blank">
<i class="icon-fw-cs"></i>
<span class="fw-title">正品保证</span>
</a>
</dt>
<dd>
<a class="fw-normal-link" href="/help/authenticguarantee" target="_blank">100%正品保证</a>
</dd>
</dl>
<dl class="fw-normal-wrap">
<dt class="fw-about-title fw-normal-dt">
<a href="/help/faq1" target="_blank">
<i class="icon-fw-question"></i>
<span class="fw-title">常见问题</span>
</a>
</dt>
<dd>
<a class="fw-normal-link" href="/help/faq1" target="_blank">为什么审核失效</a>
</dd>
<dd>
<a class="fw-normal-link" href="/help/faq2" target="_blank">账单何时生成</a>
</dd>
<dd>
<a class="fw-normal-link" href="/help/faq3" target="_blank">哪天还款</a>
</dd>
</dl>
<div class="fw-line"></div>
<section class="fw-custom-service">
<div class="fw-cs-title">客服热线</div>
<div class="fw-cs-phonenum">400-910-5151</div>
<div class="fw-cs-help">工作时间：9:00-21:00</div>
<div>北京千橡网景科技发展有限公司</div>
<div>北京市朝阳区酒仙桥中路18号</div>
<div>京网文[2013]0136-030号</div>
<div>京ICP证090254</div>
<%--<a class="fw-cs-btn" href="http://wpa.qq.com/msgrd?v=3&amp;uin=939600406&amp;site=qq&amp;menu=yes" target="_blank">在线客服</a>--%></section></div>
</footer>
