<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<meta name="keywords" content="大学生分期付款,大学生分期购物,大学生分期付款网,分期付款购物网站,分期购物商城, 电脑分期付款,手机分期付款,相机分期付款，iPhone分期付款, 小米手机，iPhone5s ，iPhone6,华为，三星，0首付, 100%正品,自定义还款期数,分期，人人分期" />
<meta name="description" content="人人分期是人人网官方唯一指定大学生分期购物平台，是人人公司旗下的权威的大学生分期购物体验商城。100%正品行货，零首付，自定义还款期数。人人分期购物商城手续便捷，有借记卡即可分期。提供手机、平板、笔记本电脑、相机等商品, 致力于打造一个安全、方便、高效、快捷的大学生购物平台。让每个学生都能买的起喜爱的商品，让每个学生从现在起积累诚信！">
<link rel="stylesheet" href="http://s.xnimg.cn/a72103/rrloan/css/base-all.css">
<script type="text/javascript">
var rrloan = { 
user: {
_rtk: '${_rtk}'
},
env: {
subdomain: 'fenqi' ,
domain: 'renren.com'
}
};	
</script>
<script src="http://s.xnimg.cn/a71894/rrloan/js/base-all.js"></script>
